# Generated by Django 5.1.3 on 2024-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0003_alter_todo_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="todo",
            name="tags",
        ),
        migrations.AddField(
            model_name="todo",
            name="tag",
            field=models.ManyToManyField(related_name="todos", to="todoApp.tag"),
        ),
    ]
