# Generated by Django 5.1.3 on 2024-11-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0004_tag_remove_todo_tags_todo_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="tag",
            new_name="tags",
        ),
    ]
